spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lyy2002/spring-cloud-config-repo
          username: 20023930@qq.com
          password: a6998546321
          basedir: C:\lyy\ideaProject\own\2019\spring-cloud-demo\config-repo
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 8888